server:
  port: 5001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yt_airline_user_db
    username: duong
    password: duong123
 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
